#:schema node_modules/wrangler/config-schema.json
name = "it-asset-keeper"
compatibility_date = "2024-04-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".output/public"

[vars]
# SUPABASE_URL = ""
# SUPABASE_PUBLISHABLE_KEY = ""
# SUPABASE_SERVICE_ROLE_KEY = ""

[observability]
enabled = true
